import { expect, test } from "@playwright/test";
import { AS_OF, offline } from "./offline";

/**
 * FR-046's minimum, over the shipped `data/`.
 *
 * Every assertion is about a state or a relation -- present, marked, refused -- and none pins a
 * figure copied out of `data/` (FR-047): the files under `data/cpi/` and `data/official_rates/`
 * are regenerated by fetch scripts and are supposed to move.
 */
test.beforeEach(async ({ page }) => {
  await offline(page);
});

test("the overview lists what the API indexes, and nothing else", async ({ page }) => {
  await page.goto(`/?as_of=${AS_OF}`);
  const cards = page.locator("[data-shape]");
  await expect(cards.first()).toBeVisible();
  const indexed = await page.evaluate(async (asOf: string) => {
    const answer = await fetch(`/api/registry?as_of=${asOf}`);
    const body: { categories: { category: string }[] } = await answer.json();
    return body.categories.map((held) => held.category);
  }, AS_OF);
  await expect(cards).toHaveCount(indexed.length);
});

test("a keyed category states a count and a singleton states whether it resolved", async ({ page }) => {
  await page.goto(`/?as_of=${AS_OF}`);
  await expect(page.locator("[data-shape='keyed']").first()).toContainText("declared");
  const singleton = page.locator("[data-shape='singleton']").first();
  await expect(singleton).toContainText("a single document");
  await expect(singleton).not.toContainText("0 declared");
});

test("opening a category shows its records, and opening one shows every field", async ({ page }) => {
  await page.goto(`/data/instruments?as_of=${AS_OF}`);
  const records = page.locator("[data-records] li a");
  await expect(records.first()).toBeVisible();
  await records.first().click();
  await expect(page.locator("[data-declared-in]")).toBeVisible();
  await expect(page.locator("[data-field]").first()).toBeVisible();
});

test("an unverified source renders its mark as text, and the field is not blank", async ({ page }) => {
  await page.goto(`/data/instruments/UA4000207518?as_of=${AS_OF}`);
  const mark = page.locator("[data-mark='unverified']").first();
  await expect(mark).toBeVisible();
  await expect(mark).toContainText("unverified");
  await expect(page.locator("[data-provenance]").first()).toContainText("retrieved_on");
});

test("a refusal from the real API is rendered as its reason, never as an empty card", async ({ page }) => {
  await page.goto(`/data/instruments/NOT-A-DECLARED-ID?as_of=${AS_OF}`);
  const refusal = page.getByRole("note").first();
  await expect(refusal).toBeVisible();
  await expect(refusal).toContainText("declares no");
  await expect(page.locator("[data-field]")).toHaveCount(0);
});

test("an as_of the router cannot validate is a visible error naming the parameter", async ({ page }) => {
  await page.goto("/?as_of=yesterday");
  const alert = page.locator("[data-parameter-error='as_of']");
  await expect(alert).toBeVisible();
  await expect(alert).toContainText("as_of");
  await expect(page.locator("[data-shape]")).toHaveCount(0);
});

test("an as_of the router's parser coerced is refused, never replaced with today", async ({ page }) => {
  // `20260905` reaches the route as a number, and a route that read it as absent would redirect
  // with the clock read instead — the silent default FR-020 forbids.
  await page.goto("/?as_of=20260905");
  const alert = page.locator("[data-parameter-error='as_of']");
  await expect(alert).toBeVisible();
  await expect(alert).toContainText("20260905");
  // The router re-serialises a numeric-looking string as a quoted one, so the URL is checked for
  // the value the reader sent rather than for their exact spelling of it.
  await expect(page).toHaveURL(/20260905/);
  await expect(page).not.toHaveURL(/as_of=\d{4}-\d{2}-\d{2}/);
});

test("an as_of written and left blank is a visible error, not a blank page", async ({ page }) => {
  await page.goto("/?as_of=");
  await expect(page.locator("[data-parameter-error='as_of']")).toBeVisible();
});

test("the official-rate chart draws, states its unit, and carries a table of the same rows", async ({ page }) => {
  await page.goto(`/series/official-rate?as_of=${AS_OF}&from=2026-08-01&to=2026-08-31`);
  const chart = page.locator("[data-chart='drawn']");
  await expect(chart).toBeVisible();
  await expect(chart).toContainText("UAH per 1 USD");
  await expect(page.locator("tbody tr").first()).toBeVisible();
});
