"""The measurement that justifies a second declaration form, made mechanical.

Feature 013 exists because of six counts read off `data/observations/inzhur.toml` on
2026-08-24, and every one of them was quoted in prose in several places. A count in prose is
the shape that goes stale silently — and this particular count already went wrong once: an
earlier draft of the specification measured *32 of 32* issues ending with two payments on one
date, and the wrong measurement hid the single issue whose list is not in date order, which is
the only one the form would have refused as published.

So the counts live here instead, as assertions over the file they were read off. The
observation is checked in, generated by `scripts/fetch_inzhur.py` and never edited by hand, so
a re-fetch that moves one of these numbers fails **here**, naming the claim that moved, rather
than leaving four docstrings quietly wrong.

⚙ **This asserts what the data says, not what the engine does.** Nothing in
`data/observations/` is wired into the engine — it exists so a declaration can be checked
against what the platform actually publishes, and so the check has a date on it.
"""

from __future__ import annotations

import tomllib
from collections import Counter
from collections.abc import Mapping, Sequence
from datetime import date
from pathlib import Path
from typing import Any, Final

import pytest

pytestmark = pytest.mark.contract

REPO_ROOT = Path(__file__).resolve().parents[2]
OBSERVATION = REPO_ROOT / "data" / "observations" / "inzhur.toml"

RETRIEVED_ON: Final = "2026-08-24"
BONDS: Final = 32
FACE_IN_MINOR_UNITS: Final = 100_000.0
ENDING_WITH_TWO_PAYMENTS_ON_ONE_DATE: Final = 31
MATURITY_DISAGREES_WITH_THE_LAST_PAYMENT: Final = 18
PUBLISHED_OUT_OF_DATE_ORDER: Final = ("UA4000235865",)
PUBLISHING_ONE_COUPON_ONLY: Final = ("UA4000230809", "UA4000232599", "UA4000233696")


def _bonds() -> Sequence[Mapping[str, Any]]:
    with OBSERVATION.open("rb") as handle:
        document = tomllib.load(handle)
    assert document["retrieved_on"] == RETRIEVED_ON, (
        "the observation was re-fetched; read the diff and re-measure the counts below "
        "before moving this date"
    )
    return [entry for entry in document["observation"] if entry.get("asset_type") == "bond"]


def _dates(bond: Mapping[str, Any]) -> list[date]:
    return [date.fromisoformat(payment["date"]) for payment in bond.get("payment", ())]


def test_the_endpoint_publishes_thirty_two_bond_issues() -> None:
    assert len(_bonds()) == BONDS


def test_not_one_of_them_publishes_an_issue_date() -> None:
    """The fact the whole form rests on. It is not given, and it is not derivable from a
    list of dated amounts — so a declaration demanding one would force an invention."""
    for bond in _bonds():
        assert "issue_date" not in bond
        assert not any(key.startswith("issued") for key in bond)


def test_none_of_them_publishes_a_coupon_rate_a_periodicity_or_a_day_count() -> None:
    """The other four terms the generative form needs. `return_rate_buy_pct` is a **yield
    quote at a price**, which is the platform's own figure about a trade rather than a term
    of the paper, and it is not a coupon rate."""
    for bond in _bonds():
        for absent in ("coupon_rate_pct", "coupon_rate", "periodicity", "day_count"):
            assert absent not in bond, bond["isin"]


def test_every_one_of_them_publishes_a_payment_of_exactly_one_hundred_thousand() -> None:
    """32 of 32, and the largest in each. This is what the inferred face value of 1 000.00
    rests on — read against buy prices near 1 000, i.e. kopecks against a 1 000.00 nominal.
    An inference, and declared as one wherever it is used."""
    for bond in _bonds():
        amounts = [payment["amount"] for payment in bond["payment"]]
        assert FACE_IN_MINOR_UNITS in amounts, bond["isin"]
        assert max(amounts) == FACE_IN_MINOR_UNITS, bond["isin"]


def test_thirty_one_of_them_end_with_two_payments_on_one_date() -> None:
    """The ordinary way a bond ends: the final coupon and the repayment of principal
    together. **31, not 32** — and the difference is the whole reason this file exists."""
    ending_together = [
        bond["isin"] for bond in _bonds() if Counter(_dates(bond))[max(_dates(bond))] == 2
    ]
    assert len(ending_together) == ENDING_WITH_TWO_PAYMENTS_ON_ONE_DATE


def test_exactly_one_publishes_its_payments_out_of_date_order() -> None:
    """The 32nd issue, and the counterexample the wrong measurement hid: it publishes the
    repayment of principal after a coupon dated a day later than it. So the single real
    exception to the pattern is the single issue the enumerated form would refuse as
    published — which is why ordering is settled at transcription and the difference is
    recorded rather than sorted away (FR-020a)."""
    unordered = [bond["isin"] for bond in _bonds() if _dates(bond) != sorted(_dates(bond))]
    assert tuple(unordered) == PUBLISHED_OUT_OF_DATE_ORDER


def test_eighteen_of_them_state_a_maturity_that_is_not_their_last_payment_date() -> None:
    """Why the enumerated form declares no maturity date: the endpoint gives one, and it
    disagrees with the last published payment in over half the issues. Accepting it would
    import that disagreement in exchange for a field nothing reads."""
    disagreeing = [
        bond["isin"]
        for bond in _bonds()
        if date.fromisoformat(bond["matures_on"]) != max(_dates(bond))
    ]
    assert len(disagreeing) == MATURITY_DISAGREES_WITH_THE_LAST_PAYMENT


def test_three_of_them_publish_only_one_coupon() -> None:
    """Why a periodicity is not derivable either: it needs two or more coupon dates, and
    three issues publish one. The coupons are the payments that are not the 100 000."""
    with_one = tuple(
        sorted(
            bond["isin"]
            for bond in _bonds()
            if len([p for p in bond["payment"] if p["amount"] != FACE_IN_MINOR_UNITS]) == 1
        )
    )
    assert with_one == PUBLISHING_ONE_COUPON_ONLY
