"""A declared calendar, and the four questions a rule written in working days would ask.

011 named the gap this fills: ``core.tax.official_rate`` says a rule written in working days
or public holidays *"cannot be declared against these records at all, because evaluating one
needs a working-day and holiday calendar and nothing declares one"*. This is that
declaration.

## Enumerated over a declared pattern, inside a declared window

A calendar is a weekly rest pattern plus an enumerated set of dates whose classification
departs from it, bounded by an explicit first and last date. Nothing here derives a holiday
from anything: a Paschalion in the engine is a legal-and-ecclesiastical fact wearing an
algorithm's clothes, which Principle I forbids, and the annual executive act that moves a
working day is arbitrary by construction and generated by no rule (FR-008).

The enumerated form goes stale at its last declared year, and the declared window is the
answer to that: **nothing extends the rest pattern past an end, repeats the last year, or
infers from an adjacent one** (FR-010), so the staleness is loud instead of silent. That was
the whole of what a generative form was being considered for -- and a generative form would
have keyed the martial-law suspension of a holiday regime to the war ending, adding one more
mechanism to a belief this system already holds elsewhere and does not know it holds twice.
An enumerated calendar conditions on nothing. **A refusal is not a belief.**

## Scope is a precondition, never a branch

A calendar asserts a jurisdiction's ``civil`` calendar or a named operator's ``settlement``
calendar, and the caller states which its question needs. **No computation here differs by
scope** -- a scope that selected an algorithm would be branching on domain knowledge, which
Principle II forbids. There is deliberately no member for a publisher's observed publication
days: those are already declared as ``OfficialRateSeries.observations``, and admitting them
would let a consumer answer *was this a working day?* from what a publisher happened to do
(FR-004).

## This module has no consumer, and that is deliberate

The sites that still decide a working day from ``primitives.conventions._is_weekend`` keep
doing so, by owner decision CL-1 of 2026-08-30: each is blocked on something other than a
calendar. ``tests/contract/test_no_calendar_free_working_day.py`` is where that set is
enumerated, so a fourth cannot appear quietly.
"""

from __future__ import annotations

from bisect import bisect_left
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import date, timedelta
from enum import Enum
from typing import Final

from terezy.core.primitives import provenance as prov
from terezy.core.primitives.provenance import Provenance

ONE_DAY: Final = timedelta(days=1)
DAYS_IN_WEEK: Final = 7

WEEKDAY_NAMES: Final[Mapping[str, int]] = {
    "monday": 0,
    "tuesday": 1,
    "wednesday": 2,
    "thursday": 3,
    "friday": 4,
    "saturday": 5,
    "sunday": 6,
}
"""``date.weekday()``'s index for each declared weekday name.

Uncited, and it needs no citation: it names the days of the week rather than saying which of
them a jurisdiction rests on. *Which* is the fact FR-002 requires declared and cited, and it
is :attr:`DeclaredWeek.rest_days`.
"""


class CalendarScope(Enum):
    """What a calendar asserts. Exactly two members, and a third would be a defect (FR-003)."""

    CIVIL = "civil"
    """Which dates a jurisdiction's law calls working, rest, holiday and pre-holiday."""

    SETTLEMENT = "settlement"
    """Which dates a named operator deals or settles on. Reserved; none is declared."""


class DecidedBy(Enum):
    """Which declared fact produced a classification (FR-012)."""

    REST_PATTERN = "rest_pattern"
    ENUMERATED_NON_WORKING_DAY = "enumerated_non_working_day"
    DECLARED_MOVE = "declared_move"


class Missed(Enum):
    """Which way an out-of-coverage question missed.

    A discriminator on one reason rather than three reasons, because the remedy differs
    within one situation. *The date was never covered* and *the date was covered and the
    answer is not* send a reader to different places: the first says the question was outside
    what anybody read the law for, the second says the question was inside it and the answer
    is one day past an edge. Which **end** to extend follows from the question rather than from
    the member: :attr:`BEFORE_WINDOW` needs the window widened earlier and :attr:`AFTER_WINDOW`
    later, :func:`first_working_day_on_or_after` running off needs it later and
    :func:`last_working_day_on_or_before` earlier -- and
    :func:`last_working_day_of_week` needs whichever end its week crosses, which is why it is
    the one case the member alone does not settle (FR-011, FR-013).
    """

    BEFORE_WINDOW = "before_window"
    AFTER_WINDOW = "after_window"
    RAN_OFF_AN_END = "ran_off_an_end"


@dataclass(frozen=True, slots=True, kw_only=True)
class DeclaredWeek:
    """The weekly rest pattern and the week start, declared together and cited once."""

    rest_days: frozenset[int]
    """``date.weekday()`` indices the jurisdiction's law makes rest days.

    Non-empty, and never all seven -- both checked at the data boundary. **Never defaulted**:
    a Saturday-and-Sunday weekend is the fact this feature is most likely to inherit from an
    implementer rather than from a source, and ``conventions._is_weekend`` asserts it
    uncited today (FR-002).
    """

    starts_on: int
    """Which weekday the jurisdiction's week begins on. Declared, because *«останній робочий
    день тижня»* cannot be answered without it and no convention here may supply it."""

    provenance: Provenance
    """The pattern's own citation."""


@dataclass(frozen=True, slots=True, kw_only=True)
class WorkingDay:
    """A date the calendar says is a working day, and which declared fact said so."""

    on_date: date
    decided_by: DecidedBy
    pre_holiday: bool
    """Whether the law shortens this working day because a holiday follows it.

    **Only a working day has this field**, which is what makes a pre-holiday non-working day
    unrepresentable rather than refused at the query (FR-012). A declaration that writes one
    is refused at load, naming the file and the date.
    """

    provenance: Provenance
    """The deciding declaration's own -- the row's, or the week's where the pattern decided."""


@dataclass(frozen=True, slots=True, kw_only=True)
class NonWorkingDay:
    """A date the calendar says is not a working day, and which declared fact said so."""

    on_date: date
    decided_by: DecidedBy
    provenance: Provenance


type DayClassification = WorkingDay | NonWorkingDay


@dataclass(frozen=True, slots=True, kw_only=True)
class DeclaredHoliday:
    """A date the law names a public holiday. Non-working whatever the pattern says."""

    on_date: date
    provenance: Provenance


@dataclass(frozen=True, slots=True, kw_only=True)
class DeclaredRestDay:
    """A date a declared act made a rest day. Refused at load where the pattern already rests
    it, because a row that repeats the pattern would be reported as a move that never
    happened."""

    on_date: date
    provenance: Provenance


@dataclass(frozen=True, slots=True, kw_only=True)
class DeclaredWorkingDay:
    """A date the law works, and whether it shortens it because a holiday follows.

    **Two different declarations wear this shape**, and :func:`classify` tells them apart from
    the pattern rather than from the row: a rest day an act moved into working status is
    decided by that move, while an ordinary working day declared *pre-holiday* is decided by
    the rest pattern and the row only adds the shortening. Baking a move into every row of
    this kind would report an executive act on a Friday no act touched -- the false statement
    in exactly the field FR-012 exists to make traceable.
    """

    on_date: date
    pre_holiday: bool
    provenance: Provenance


type ClassificationRow = DeclaredHoliday | DeclaredRestDay | DeclaredWorkingDay
"""One date whose declaration departs from the rest pattern. A pre-holiday non-working day is
unrepresentable here, and so is a row carrying no classification at all."""


@dataclass(frozen=True, slots=True, kw_only=True)
class WorkingDayCalendar:
    """One declared calendar: an identity, a scope, a window, a week and its exceptions."""

    id: str
    """How a consumer reaches it. Never selected by jurisdiction, scope or load order: a
    jurisdiction may legitimately have both a civil calendar and a venue's settlement one,
    and picking between them by jurisdiction would decide a legal question by directory
    contents (FR-003a)."""

    jurisdiction: str
    authority: str
    scope: CalendarScope

    covers: tuple[date, date]
    """First and last date this calendar speaks for. Two-ended, declared, never inferred from
    the rows: a calendar with no window is one that never refuses."""

    covered_by: Provenance
    """The window's own citation, and an input to **every** answer this calendar gives.

    The absence of a row means *the law declared no exception here* only because somebody read
    the law for this window; without that claim it would mean *nobody transcribed this date*,
    and the two are opposite. So :func:`classify` marks every answer with this as well as with
    the declaration that decided it, and a calendar whose window is unverified marks even the
    dates its rest pattern settled.

    It is also the only home an **empty enumeration** has: a year whose holiday regime a
    statute suspended declares no rows, and the suspending act is cited here.
    """

    week: DeclaredWeek

    rows: tuple[ClassificationRow, ...]
    """The enumerated exceptions, strictly ascending by date, each dated inside the window.

    **Empty is a statement, not a gap** -- see :attr:`covered_by`, which is where a suspended
    year's citation goes.
    """


@dataclass(frozen=True, slots=True, kw_only=True)
class CalendarNotDeclared:
    """No calendar carries this id. Carries no window: none was found to have one."""

    wanted_id: str
    reason: str


@dataclass(frozen=True, slots=True, kw_only=True)
class CalendarScopeMismatch:
    """The named calendar exists and asserts something else."""

    calendar_id: str
    scope_wanted: CalendarScope
    scope_found: CalendarScope
    reason: str


@dataclass(frozen=True, slots=True, kw_only=True)
class CalendarOutOfCoverage:
    """The named calendar has the right scope and does not reach the date."""

    calendar_id: str
    on_date: date
    covers: tuple[date, date]
    missed: Missed
    reason: str


type CalendarUnavailable = CalendarNotDeclared | CalendarScopeMismatch | CalendarOutOfCoverage
"""Why no classification could be produced. Three members, three remedies.

There is deliberately no *this jurisdiction has no calendar* member: FR-003a forbids the
engine from looking a calendar up by jurisdiction, so nothing can discover that a
jurisdiction has none, and the reason would be a guard whose message is false.
"""


def _reached(
    calendars: Mapping[str, WorkingDayCalendar], calendar_id: str, scope: CalendarScope
) -> WorkingDayCalendar | CalendarNotDeclared | CalendarScopeMismatch:
    """The named calendar, or the refusal that says why it was not reached."""
    found = calendars.get(calendar_id)
    if found is None:
        return CalendarNotDeclared(
            wanted_id=calendar_id,
            reason=(
                f"no declared calendar carries the id {calendar_id!r}. A calendar is reached "
                f"by naming it; known ids: {sorted(calendars)}."
            ),
        )
    if found.scope is not scope:
        return CalendarScopeMismatch(
            calendar_id=calendar_id,
            scope_wanted=scope,
            scope_found=found.scope,
            reason=(
                f"calendar {calendar_id!r} asserts a {found.scope.value} calendar and the "
                f"question needs a {scope.value} one. A jurisdiction's law and an operator's "
                "dealing days genuinely differ, so the wrong kind is refused rather than "
                "answered from."
            ),
        )
    return found


def _outside(calendar: WorkingDayCalendar, on_date: date) -> CalendarOutOfCoverage | None:
    """The refusal for a date past either end of the window, or ``None`` for one inside."""
    first, last = calendar.covers
    if first <= on_date <= last:
        return None
    missed = Missed.BEFORE_WINDOW if on_date < first else Missed.AFTER_WINDOW
    return _out_of_coverage(calendar, on_date, missed)


def _out_of_coverage(
    calendar: WorkingDayCalendar, on_date: date, missed: Missed
) -> CalendarOutOfCoverage:
    first, last = calendar.covers
    window = f"{first.isoformat()} to {last.isoformat()}"
    told = {
        Missed.BEFORE_WINDOW: "before the first date it covers",
        Missed.AFTER_WINDOW: "after the last date it covers",
        Missed.RAN_OFF_AN_END: (
            "inside the window, but answering it needs a date outside. Extending the "
            "calendar is what fixes this one"
        ),
    }[missed]
    return CalendarOutOfCoverage(
        calendar_id=calendar.id,
        on_date=on_date,
        covers=calendar.covers,
        missed=missed,
        reason=(
            f"calendar {calendar.id!r} covers {window} and {on_date.isoformat()} is {told}. "
            "The declared rest pattern is not extended past either end."
        ),
    )


def _row_on(calendar: WorkingDayCalendar, on_date: date) -> ClassificationRow | None:
    """The enumerated exception for a date, by bisection over the ascending rows."""
    position = bisect_left(calendar.rows, on_date, key=lambda row: row.on_date)
    if position < len(calendar.rows) and calendar.rows[position].on_date == on_date:
        return calendar.rows[position]
    return None


def rests_on(week: DeclaredWeek, on_date: date) -> bool:
    """Whether the declared rest pattern alone makes this date a rest day."""
    return on_date.weekday() in week.rest_days


def _classified(calendar: WorkingDayCalendar, on_date: date) -> DayClassification:
    """A covered date's classification, and which declared fact decided it.

    Every answer carries the coverage window's citation as well as the deciding
    declaration's: *no row for this date* means *the law declared no exception here* only
    because somebody read the law for this window.
    """
    pattern = prov.merge(calendar.covered_by, calendar.week.provenance)
    row = _row_on(calendar, on_date)
    if row is None:
        if rests_on(calendar.week, on_date):
            return NonWorkingDay(
                on_date=on_date, decided_by=DecidedBy.REST_PATTERN, provenance=pattern
            )
        return WorkingDay(
            on_date=on_date,
            decided_by=DecidedBy.REST_PATTERN,
            pre_holiday=False,
            provenance=pattern,
        )
    cited = prov.merge(calendar.covered_by, row.provenance)
    # A verdict read off the pattern rests on the pattern, whichever way it comes out.
    # `DECLARED_MOVE` is the claim that an act moved this date, and the only evidence anything
    # was moved is the rest pattern saying the date would otherwise go the other way -- so an
    # unverified pattern must mark a moved answer exactly as it marks a pattern-decided one.
    # `ENUMERATED_NON_WORKING_DAY` is the one verdict that does not consult it: that the law
    # names a date a holiday is true of a Sunday and a Tuesday alike.
    against_the_pattern = prov.merge(cited, calendar.week.provenance)
    match row:
        case DeclaredHoliday():
            return NonWorkingDay(
                on_date=on_date,
                decided_by=DecidedBy.ENUMERATED_NON_WORKING_DAY,
                provenance=cited,
            )
        case DeclaredRestDay():
            return NonWorkingDay(
                on_date=on_date,
                decided_by=DecidedBy.DECLARED_MOVE,
                provenance=against_the_pattern,
            )
        case DeclaredWorkingDay():
            return WorkingDay(
                on_date=on_date,
                decided_by=(
                    DecidedBy.DECLARED_MOVE
                    if rests_on(calendar.week, on_date)
                    else DecidedBy.REST_PATTERN
                ),
                pre_holiday=row.pre_holiday,
                provenance=against_the_pattern,
            )


def classify(
    calendars: Mapping[str, WorkingDayCalendar],
    calendar_id: str,
    *,
    scope: CalendarScope,
    on_date: date,
) -> DayClassification | CalendarUnavailable:
    """Whether a date is a working day, and which declared fact decided it (FR-012)."""
    reached = _reached(calendars, calendar_id, scope)
    if not isinstance(reached, WorkingDayCalendar):
        return reached
    refused = _outside(reached, on_date)
    return refused if refused is not None else _classified(reached, on_date)


def _search(
    calendar: WorkingDayCalendar, from_date: date, step: timedelta, within: tuple[date, date]
) -> WorkingDay | None:
    """The first working day from ``from_date`` in ``step``'s direction, inside ``within``.

    ``within`` is an argument rather than :attr:`WorkingDayCalendar.covers` because the two
    searches bound differently and one of them silently gives a wrong answer if it borrows the
    other's bound: *the last working day of this week* searched to the window's edge would walk
    out of the week and return a date from the one before it -- a plausible answer to a
    question nobody asked.
    """
    first, last = within
    day = from_date
    while first <= day <= last:
        found = _classified(calendar, day)
        if isinstance(found, WorkingDay):
            return found
        day += step
    return None


def _walk(
    calendars: Mapping[str, WorkingDayCalendar],
    calendar_id: str,
    scope: CalendarScope,
    on_date: date,
    step: timedelta,
) -> WorkingDay | CalendarUnavailable:
    """FR-013's search, in whichever direction: reach the calendar, then walk the window.

    A search that would leave the window refuses with :attr:`Missed.RAN_OFF_AN_END` rather
    than returning the window's edge or looping. The two directions are one function because
    they were the same six lines twice, and a repeated walk is where a bound drifts.
    """
    reached = _reached(calendars, calendar_id, scope)
    if not isinstance(reached, WorkingDayCalendar):
        return reached
    refused = _outside(reached, on_date)
    if refused is not None:
        return refused
    found = _search(reached, on_date, step, reached.covers)
    return found if found is not None else _out_of_coverage(reached, on_date, Missed.RAN_OFF_AN_END)


def first_working_day_on_or_after(
    calendars: Mapping[str, WorkingDayCalendar],
    calendar_id: str,
    *,
    scope: CalendarScope,
    on_date: date,
) -> WorkingDay | CalendarUnavailable:
    """The first working day on or after a date, skipping every consecutive rest day."""
    return _walk(calendars, calendar_id, scope, on_date, ONE_DAY)


def last_working_day_on_or_before(
    calendars: Mapping[str, WorkingDayCalendar],
    calendar_id: str,
    *,
    scope: CalendarScope,
    on_date: date,
) -> WorkingDay | CalendarUnavailable:
    """The last working day on or before a date. FR-013's other half, which пункт 10 does not
    name and a carry-forward rule does."""
    return _walk(calendars, calendar_id, scope, on_date, -ONE_DAY)


def last_working_day_of_week(
    calendars: Mapping[str, WorkingDayCalendar],
    calendar_id: str,
    *,
    scope: CalendarScope,
    on_date: date,
) -> WorkingDay | CalendarUnavailable:
    """The last working day of the week containing a date, from the declared week start.

    **A week straddling either end of the window refuses**, with
    :attr:`Missed.RAN_OFF_AN_END`, even where a working day exists inside the window:
    answering from the visible part would return a plausible date that is not the answer to
    the question asked (FR-014).
    """
    reached = _reached(calendars, calendar_id, scope)
    if not isinstance(reached, WorkingDayCalendar):
        return reached
    refused = _outside(reached, on_date)
    if refused is not None:
        return refused
    starts, ends = _week_bounds(reached.week, on_date)
    first, last = reached.covers
    if starts < first or ends > last:
        return _out_of_coverage(reached, on_date, Missed.RAN_OFF_AN_END)
    found = _search(reached, ends, -ONE_DAY, (starts, ends))
    if found is None:
        raise ValueError(
            f"calendar {reached.id!r} declares no working day in the week beginning "
            f"{starts.isoformat()}, which lies wholly inside its coverage window. "
            f"{week_without_a_working_day.__name__} refuses such a calendar at the data "
            "boundary, so this one was built without passing it."
        )
    return found


def _week_bounds(week: DeclaredWeek, on_date: date) -> tuple[date, date]:
    """The first and last dates of the week containing ``on_date``, by its declared start."""
    starts = on_date - ONE_DAY * ((on_date.weekday() - week.starts_on) % DAYS_IN_WEEK)
    return starts, starts + ONE_DAY * (DAYS_IN_WEEK - 1)


def week_without_a_working_day(calendar: WorkingDayCalendar) -> date | None:
    """The start of the first week inside the window that holds no working day, or ``None``.

    The data boundary calls this and refuses, for the reason an all-seven rest pattern is
    refused there: every working-day question would then produce a refusal naming the *date*,
    sending a reader to fix a date when the declaration is what is wrong. Seven consecutive
    enumerated non-working rows reach that state by another road, and FR-011 fixes the refusal
    union at three reasons -- none of which is *this week has no working day*.

    Weeks straddling either end are skipped: :func:`last_working_day_of_week` refuses those
    with the ran-off-an-end discriminator, so they need no working day at all.
    """
    first, last = calendar.covers
    starts, ends = _week_bounds(calendar.week, first)
    if starts < first:
        starts, ends = starts + ONE_DAY * DAYS_IN_WEEK, ends + ONE_DAY * DAYS_IN_WEEK
    while ends <= last:
        if _search(calendar, starts, ONE_DAY, (starts, ends)) is None:
            return starts
        starts, ends = starts + ONE_DAY * DAYS_IN_WEEK, ends + ONE_DAY * DAYS_IN_WEEK
    return None
